spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:youremail@gmail.com}
    password: ${SMTP_PASSWORD:16digit app code}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true     # 587/TLS용
          # ssl:
          #   enable: true   # 465/SSL을 쓸 땐 위 2줄 대신 이 줄을 켜세요

email:
  from: ${EMAIL_FROM:no-reply@gmail.com}
  subject-prefix: "[동아리 지원]"
